### ISSUE TITLE
SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

### ISSUE THREAD

**Issue by tanmaythakur** [ckan/datapusher#83] opened 2015-09-08 22:40 UTC
My CKAN instance is running on self-signed certificate. When I try to upload to datastore, I see "SSL3_GET_SERVER_CERTIFICATE:certificate verify failed" error.

**Comment by mattfullerton** [comment] 2015-10-08 13:07
Its not only a problem with self-signed certificates, but also some complicated perfectly healthy ones.

I have tracked down the cause of this, at least for the instance I'm working with right now. Python has SSL issues pre 2.7.9:
http://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning

I get no problems with 2.7.10, but get the error with pre 2.7.9 versions. Again let me stress, this is a perfectly healthy certificate.

### Why?

Datapusher accesses CKAN using ckan_url from .ini file - i.e. the external URL, in order to work with the API. This is one of the few places, if perhaps the only place, where a part of a CKAN install accesses CKAN from the outside. It's an external service, so it sort of has to. I'm wondering what the easiest/best fix is:

- Tell people to use >2.7.9 if they plan on using datapusher and ssl. This is a big ask as changing the system or environment python is not so straightforward or possible.
- Add configuration variables for datapusher for how to access CKAN via an internal url given that usually it is running on the same server, i.e. datapusher.internalckanurl = 127.0.0.1:8080

**Comment by mattfullerton** [comment] 2015-10-08 13:12
P.S.: The second option would solve @tanmaythakur 's problem as well because the datapusher would never have to interact with the SSL (SSL in CKAN always happens at some proxy level). It seems a little silly in general that a completely internal service is having to do a big loop like this.

**Comment by amercader** [comment] 2015-10-26 12:40
@mattfullerton Not super keen on the first option :)

The way datapusher (or rather ckan service provider) works is that CKAN (or whatever app) will send the callback url that needs to be notified when a particular job is done (`result_url` in http://ckan-service-provider.readthedocs.org/en/latest/#post--job). This is set up in CKAN [here](https://github.com/ckan/ckan/blob/master/ckanext/datapusher/logic/action.py#L53) using `ckan.site_url`.
With that in mind I think that the configuration should be done at the CKAN level. Perhaps something like

```
ckan.internal_site_url=http://127.0.0.1:8080
datapusher.use_internal_ckan_url=True
```

**Comment by kapucko** [comment] 2015-11-10 08:12
Hi,

I have the same problem as @tanmaythakur and I like his solution. Do you have any idea when his pull request is going to be merged into the master?

**Comment by mattfullerton** [comment] 2015-11-10 08:39
It doesn't look like @tanmaythakur wanted his solution to be merged, the documentation says do not use in production. The suggestion from @amercader just needs to be coded.

**Comment by tanmaythakur** [comment] 2015-11-10 23:43
@kapucko Feel free to use https://github.com/tanmaythakur/datapusher/tree/toggle_ssl_verification 
I have a introduced a configuration variable to toggle the SSL verification. It can be set to true or false and can be used in production. 

Read more : https://github.com/tanmaythakur/datapusher/tree/toggle_ssl_verification#configuration

**Comment by mattfullerton** [comment] 2016-05-18 09:05
@tanmaythakur - could you send this as a pull request?
@amercader - is the solution acceptable

**Comment by metaodi** [comment] 2017-03-02 07:42
With #109 merged we now have at least the option to disable the verification. Which leaves us with the problem of the _perfectly healthy certificates_ that @mattfullerton describes.

On our instance we could solve this by installing both [`certifi`](https://pypi.python.org/pypi/certifi) and by using the security extra set of requests (`pip install requests[security]`). This might be worth a PR as well. cc @stefina

**Comment by stefina** [comment] 2017-03-09 17:35
PR #117 was accidentially closed. To include the security-option in requests and add certifi as @metaodi stated, #120 is the new PR.
Sorry for the confusion it may cause.

**Comment by davidread** [comment] 2017-04-04 09:55
Closing now #120 is merged.

**Closed by davidread** 2017-04-04 09:55 UTC

**Comment by derwas** [comment] 2018-06-07 21:11
Hey @mattfullerton I am experiencing a related issue. I am running multiple ckan instances with single datapusher (all on the same server).  -- I guess you know where I am coming from :)

Datapusher seems to accept the ssl cert and passes only jobs from one of the instances! If I push data from another instance, datapusher does not find a proper matching of ckan url and the passed ssl cert! I am interested to get back to and test your proposed Option 2. Do you have further details? or Is there a way to disable ssl certificate verification in datapusher?

**Comment by mattfullerton** [comment] 2018-06-09 07:13
Hi @derwas :slightly_smiling_face: 
So just to check, the problem is not SSL related, and wouldn't be fixed with the PR discussed above; rather you want to have the ability to specify an internal URL to make things simpler, as discussed by me and @amercader above, right? Unfortunately those are the only details there are. The place to implement such a change would probably be here:
https://github.com/ckan/ckan/blob/master/ckanext/datapusher/logic/action.py#L64

I suppose the reason its only working on one CKAN is that one of them shares the same hostname as something that maps correctly to the datapusher. Maybe a simple change in the hosts file would help datapusher find the right IPs for the other CKANs? Though if its docker then these might be changing... ouch, my head hurts...!

**Comment by derwas** [comment] 2018-06-09 08:51
Hey @mattfullerton, You guessed it, it's docker, each instance run on a separate container and datapusher on another one. In the worst case I'll have to setup multiple datapushers, one for each chan instance, but that's an overkill!!!

**Comment by ansh1221** [comment] 2019-05-10 14:02
Hey @mattfullerton @amercader @tanmaythakur

I have upgraded my python>2.7.9 and used SSL_VERIFY=False also installed the datapusher in the same container as CKAN. Still it is displaying the following error:

```
root@08020d0c6563:/home/datapusher# python datapusher/main.py deployment/datapusher_settings.py
 * Running on http://0.0.0.0:8800/ (Press CTRL+C to quit)
127.0.0.1 - - [10/May/2019 13:56:35] "POST /job HTTP/1.1" 200 -
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Job "push_to_datastore (trigger: RunTriggerNow, run = True, next run at: None)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/scheduler.py", line 512, in _run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/datapusher/datapusher/jobs.py", line 326, in push_to_datastore
    resource = get_resource(resource_id, ckan_url, api_key)
  File "/home/datapusher/datapusher/jobs.py", line 276, in get_resource
    'Authorization': api_key}
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
127.0.0.1 - - [10/May/2019 13:56:35] "GET /job/9575ef71-3d76-4ce5-aecc-e36067fdc26b HTTP/1.1" 200 
```-

Have been working on it, but unfortunately have not been able to run it in docker. and yes CKAN is being served via nginx.
