### ISSUE TITLE
The data was invalid error for many large csv files!

### ISSUE THREAD

**Issue by moqri** [ckan/datapusher#105] opened 2016-10-04 22:03 UTC
It seems the messytable.py used in datapusher guess the types of column by looking at a sample of the data (top 1000 rows maybe)
For large tables (csv files), this is giving me error for most of my files. Most of the time to top rows for a column are all numeric while further down there is a non-numeric data which is not convertible to number by messytable casting methods.
For example if there is a "1/2" value in a column, the column will be "guessed" as numeric and datapusher chokes when uploading the data.
Example:
http://52.41.50.184/dataset/california-01/resource_data/09e74ee2-19ea-4fe5-bb41-12170bfefb55
Any quick fix?

**Comment by mckaydavis** [comment] 2016-12-03 02:48
Looks like a duplicate of #48 -- @Moqri check there for a possible solution.

**Comment by davidread** [comment] 2017-04-04 09:07
Yes, closing in favour of #48

**Closed by davidread** 2017-04-04 09:07 UTC
